services:
  - type: web
    name: biblioteca-escolar
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run_server.py
    plan: free
    autoDeploy: false
    envVars:
      - key: HOST
        value: "0.0.0.0"
      - key: PYTHON_VERSION
        value: "3.11.0"